CREATE TABLE User_def (
    ID VARCHAR(36) NOT NULL ,
    NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    CODE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    BIRTHDATE DATETIME DEFAULT NULL,
    PASSWORD VARCHAR(100),
    PASSWORD_HISTORY json,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UQ_SEC_USER_DEF` (`EMAIL`)
 );