CREATE TABLE User_def (
    ID VARCHAR NOT NULL PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    LAST_NAME VARCHAR NOT NULL,
    CODE VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL,
    BIRTHDATE datetime DEFAULT NULL,
    PASSWORD VARCHAR,
    PASSWORD_HISTORY json
 );